// src/lib/mockData.js
export const MOCK_PRODUCTS = [
  { id: '1', brand: 'Maison Aurum',       name: 'Eternal Rose Diamond Ring',    description: 'A masterpiece of 18k rose gold adorned with 0.8ct VS1 diamonds. Each stone hand-selected for exceptional brilliance and clarity.', price: 285000,  category: 'Jewellery',   emoji: '💍', stock: 5,  tags: ['bestseller','new arrival'], badge: 'Bestseller', rating: 4.9, reviews: 128 },
  { id: '2', brand: 'Aurum Horlogerie',   name: 'Grand Perpetual Tourbillon',   description: 'An extraordinary achievement in watchmaking. Self-winding tourbillon movement with 72-hour power reserve and exhibition caseback.', price: 1850000, category: 'Watches',     emoji: '⌚', stock: 2,  tags: ['limited edition'],           badge: 'Limited',    rating: 5.0, reviews: 24  },
  { id: '3', brand: 'Casa Aurum',         name: "Nuit d'Or Parfum",             description: 'An intoxicating blend of rare Damascene rose, aged oud from the forests of Assam, and white amber. Lasts 18+ hours on skin.',       price: 45000,   category: 'Fragrance',   emoji: '🌹', stock: 20, tags: ['new arrival'],               badge: null,         rating: 4.8, reviews: 89  },
  { id: '4', brand: 'Aurum Maroquinerie', name: 'Regent Tote Éclat',            description: 'Hand-stitched by master artisans in Florence from butter-soft full-grain calfskin. Gold-plated hardware, suede interior.',           price: 125000,  category: 'Accessories', emoji: '👜', stock: 8,  tags: ['new arrival'],               badge: 'New',        rating: 4.7, reviews: 56  },
  { id: '5', brand: 'Maison Aurum',       name: 'Celestine Sapphire Necklace',  description: 'A single 3.5ct Kashmir sapphire, unheated and GRS-certified, suspended on a hand-forged 18k white gold chain with pavé bail.',     price: 520000,  category: 'Jewellery',   emoji: '💙', stock: 1,  tags: ['rare','limited edition'],    badge: 'Rare',       rating: 5.0, reviews: 12  },
  { id: '6', brand: 'Aurum Horlogerie',   name: 'Calendrier Perpétuel Noir',    description: 'Matte black PVD titanium case with perpetual calendar and moon-phase display. Swiss automatic movement, 300m water resistance.',      price: 395000,  category: 'Watches',     emoji: '🖤', stock: 4,  tags: ['bestseller'],                badge: null,         rating: 4.9, reviews: 67  },
  { id: '7', brand: 'Casa Aurum',         name: 'Amber Soleil Extrait',          description: 'A solar accord of Sicilian bergamot, orris butter, and Haitian vetiver. Hand-blown Venetian glass bottle. 100ml.',                   price: 38000,   category: 'Fragrance',   emoji: '🧡', stock: 15, tags: ['new arrival'],               badge: null,         rating: 4.6, reviews: 43  },
  { id: '8', brand: 'Aurum Maroquinerie', name: 'Windsor Briefcase Obsidian',   description: 'Corporate luxury redefined. Full-grain obsidian leather, hand-painted edges, and 14k gold-plated solid brass fittings. 15" laptop fits.', price: 185000, category: 'Accessories', emoji: '💼', stock: 6, tags: ['bestseller'],               badge: null,         rating: 4.8, reviews: 91  },
  { id: '9', brand: 'Maison Aurum',       name: 'Riviera Emerald Bracelet',     description: 'Colombian emeralds totalling 4.2ct set in a flexible 18k yellow gold bracelet. Accompanied by Swiss gemological certificate.',         price: 780000,  category: 'Jewellery',   emoji: '💚', stock: 3,  tags: ['rare'],                      badge: 'Rare',       rating: 4.9, reviews: 18  },
  { id:'10', brand: 'Aurum Horlogerie',   name: 'Skeleton Moonphase Rose',      description: 'Skeletonised movement visible through sapphire crystals front and back. Rose gold case, hand-stitched alligator strap.',               price: 620000,  category: 'Watches',     emoji: '🌕', stock: 3,  tags: ['new arrival','limited edition'], badge: 'New',    rating: 4.8, reviews: 31  },
];

export const MOCK_ORDERS = [
  { id: 'ORD-2024-001', customer_name: 'Priya Mehta',   product_summary: 'Eternal Rose Diamond Ring',  total: 285000,  status: 'delivered',  created_at: '2024-06-18T10:00:00Z' },
  { id: 'ORD-2024-002', customer_name: 'Rajiv Shah',    product_summary: 'Grand Perpetual Tourbillon', total: 1850000, status: 'processing', created_at: '2024-06-20T14:30:00Z' },
  { id: 'ORD-2024-003', customer_name: 'Ananya Bose',   product_summary: "Nuit d'Or Parfum",           total: 45000,   status: 'shipped',    created_at: '2024-06-21T09:15:00Z' },
  { id: 'ORD-2024-004', customer_name: 'Vikram Nair',   product_summary: 'Windsor Briefcase Obsidian', total: 185000,  status: 'delivered',  created_at: '2024-06-22T16:45:00Z' },
];
