// src/lib/mockData.js
export const MOCK_PRODUCTS = [
  { id: '1', brand: 'Maison Aurum',       name: 'Eternal Rose Diamond Ring',    description: 'A masterpiece of 18k rose gold adorned with 0.8ct VS1 diamonds. Each stone hand-selected for exceptional brilliance and clarity.', price: 285000,  category: 'Jewellery',   emoji: '💍', stock: 5,  tags: ['bestseller','new arrival'], badge: 'Bestseller', rating: 4.9, reviews: 128 },
  { id: '2', brand: 'Aurum Horlogerie',   name: 'Grand Perpetual Tourbillon',   description: 'An extraordinary achievement in watchmaking. Self-winding tourbillon movement with 72-hour power reserve and exhibition caseback.', price: 1850000, category: 'Watches',     emoji: '⌚', stock: 2,  tags: ['limited edition'],           badge: 'Limited',    rating: 5.0, reviews: 24  },
  { id: '3', brand: 'Casa Aurum',         name: "Nuit d'Or Parfum",             description: 'An intoxicating blend of rare Damascene rose, aged oud from the forests of Assam, and white amber. Lasts 18+ hours on skin.',       price: 45000,   category: 'Fragrance',   emoji: '🌹', stock: 20, tags: ['new arrival'],               badge: null,         rating: 4.8, reviews: 89  },
  { id: '4', brand: 'Aurum Maroquinerie', name: 'Regent Tote Éclat',            description: 'Hand-stitched by master artisans in Florence from butter-soft full-grain calfskin. Gold-plated hardware, suede interior.',           price: 125000,  category: 'Accessories', emoji: '👜', stock: 8,  tags: ['new arrival'],               badge: 'New',        rating: 4.7, reviews: 56  },
  { id: '5', brand: 'Maison Aurum',       name: 'Celestine Sapphire Necklace',  description: 'A single 3.5ct Kashmir sapphire, unheated and GRS-certified, suspended on a hand-forged 18k white gold chain with pavé bail.',     price: 520000,  category: 'Jewellery',   emoji: '💙', stock: 1,  tags: ['rare','limited edition'],    badge: 'Rare',       rating: 5.0, reviews: 12  },
  { id: '6', brand: 'Aurum Horlogerie',   name: 'Calendrier Perpétuel Noir',    description: 'Matte black PVD titanium case with perpetual calendar and moon-phase display. Swiss automatic movement, 300m water resistance.',      price: 395000,  category: 'Watches',     emoji: '🖤', stock: 4,  tags: ['bestseller'],                badge: null,         rating: 4.9, reviews: 67  },
  { id: '7', brand: 'Casa Aurum',         name: 'Amber Soleil Extrait',          description: 'A solar accord of Sicilian bergamot, orris butter, and Haitian vetiver. Hand-blown Venetian glass bottle. 100ml.',                   price: 38000,   category: 'Fragrance',   emoji: '🧡', stock: 15, tags: ['new arrival'],               badge: null,         rating: 4.6, reviews: 43  },
  { id: '8', brand: 'Aurum Maroquinerie', name: 'Windsor Briefcase Obsidian',   description: 'Corporate luxury redefined. Full-grain obsidian leather, hand-painted edges, and 14k gold-plated solid brass fittings. 15" laptop fits.', price: 185000, category: 'Accessories', emoji: '💼', stock: 6, tags: ['bestseller'],               badge: null,         rating: 4.8, reviews: 91  },
  { id: '9', brand: 'Maison Aurum',       name: 'Riviera Emerald Bracelet',     description: 'Colombian emeralds totalling 4.2ct set in a flexible 18k yellow gold bracelet. Accompanied by Swiss gemological certificate.',         price: 780000,  category: 'Jewellery',   emoji: '💚', stock: 3,  tags: ['rare'],                      badge: 'Rare',       rating: 4.9, reviews: 18  },
  { id:'10', brand: 'Aurum Horlogerie',   name: 'Skeleton Moonphase Rose',      description: 'Skeletonised movement visible through sapphire crystals front and back. Rose gold case, hand-stitched alligator strap.',               price: 620000,  category: 'Watches',     emoji: '🌕', stock: 3,  tags: ['new arrival','limited edition'], badge: 'New',    rating: 4.8, reviews: 31  },
  { id:'11', brand: 'Maison Aurum',       name: 'Duchess Cashmere Overcoat',    description: 'Double-faced pure cashmere in midnight navy. Crafted by hand in our Florence atelier with horn buttons and silk-satin lining. A singular garment built to last generations.', price: 385000, category: 'Clothing', emoji: '🧥', stock: 4,  tags: ['new arrival','limited edition'], badge: 'New',    rating: 4.9, reviews: 22  },
  { id:'12', brand: 'Aurum Couture',      name: 'Silk Charmeuse Evening Gown',  description: 'Pure 22-momme silk charmeuse, bias-cut and hand-finished. The fluid drape and champagne ivory tone are understated perfection for black-tie occasions.',                price: 295000, category: 'Clothing', emoji: '👗', stock: 3,  tags: ['limited edition'],              badge: 'Limited', rating: 4.8, reviews: 14  },
  { id:'13', brand: 'Aurum Couture',      name: 'Bespoke Wool Suit Noir',       description: 'Hand-tailored in 120s super-fine English wool. Two-button silhouette, hand-sewn lapels, and full canvas construction. Includes two fittings at our boutique.',              price: 450000, category: 'Clothing', emoji: '🤵', stock: 6,  tags: ['bestseller'],                   badge: null,     rating: 5.0, reviews: 38  },
  { id:'14', brand: 'Maison Aurum',       name: 'Heritage Linen Shirt',         description: 'Portuguese linen of the finest weave, stonewashed for a lived-in softness. Mother-of-pearl buttons. Available in ivory, sand, and slate blue.',                           price: 28000,  category: 'Clothing', emoji: '👕', stock: 18, tags: ['new arrival','bestseller'],     badge: null,     rating: 4.7, reviews: 61  },
  { id:'15', brand: 'Aurum Couture',      name: 'Velvet Smoking Jacket',        description: 'Midnight blue silk-velvet with grosgrain lapels. Peak-lapel single-button cut inspired by the great tailors of Savile Row. Fully lined in bespoke paisley silk.',          price: 195000, category: 'Clothing', emoji: '🎩', stock: 5,  tags: ['rare'],                         badge: 'Rare',   rating: 4.9, reviews: 17  },
  { id:'16', brand: 'Maison Aurum',       name: 'Pashmina Shawl Or & Noir',     description: 'The finest grade-A Pashmina from Ladakh — 12 microns. Hand-woven and hand-embroidered by master artisans in Srinagar. One shawl takes six months to complete.',         price: 75000,  category: 'Clothing', emoji: '🧣', stock: 9,  tags: ['new arrival'],                  badge: 'New',    rating: 4.9, reviews: 29  },
];

export const MOCK_ORDERS = [
  {
    id: 'a1111111-1111-4111-8111-111111111111',
    user_id: 'demo-user-1',
    customer_name: 'Priya Mehta',
    status: 'delivered',
    subtotal: 285000,
    tax: 51300,
    total: 336300,
    payment_id: 'pay_demo_001',
    payment_method: 'razorpay',
    tracking_number: 'AUR-IN-88341',
    carrier: 'Bluedart Premium',
    estimated_delivery: '2024-06-22',
    status_updated_at: '2024-06-21T11:20:00Z',
    created_at: '2024-06-18T10:00:00Z',
    address: {
      full_name: 'Priya Mehta', email: 'priya.mehta@example.com', phone: '+91 98200 11223',
      line1: '14 Carmichael Road', line2: 'Cumballa Hill', city: 'Mumbai', state: 'Maharashtra',
      pincode: '400026', country: 'India',
    },
    order_items: [
      { id: 'oi1', product_name: 'Eternal Rose Diamond Ring', price: 285000, quantity: 1,
        products: { name: 'Eternal Rose Diamond Ring', emoji: '💍' } },
    ],
  },
  {
    id: 'a2222222-2222-4222-8222-222222222222',
    user_id: 'demo-user-2',
    customer_name: 'Rajiv Shah',
    status: 'processing',
    subtotal: 1850000,
    tax: 333000,
    total: 2183000,
    payment_id: 'pay_demo_002',
    payment_method: 'razorpay',
    tracking_number: null,
    carrier: null,
    estimated_delivery: '2024-06-27',
    status_updated_at: '2024-06-20T15:10:00Z',
    created_at: '2024-06-20T14:30:00Z',
    address: {
      full_name: 'Rajiv Shah', email: 'rajiv.shah@example.com', phone: '+91 98100 44556',
      line1: '7 Golf Links', line2: '', city: 'New Delhi', state: 'Delhi',
      pincode: '110003', country: 'India',
    },
    order_items: [
      { id: 'oi2', product_name: 'Grand Perpetual Tourbillon', price: 1850000, quantity: 1,
        products: { name: 'Grand Perpetual Tourbillon', emoji: '⌚' } },
    ],
  },
  {
    id: 'a3333333-3333-4333-8333-333333333333',
    user_id: 'demo-user-3',
    customer_name: 'Ananya Bose',
    status: 'shipped',
    subtotal: 45000,
    tax: 8100,
    total: 53100,
    payment_id: 'pay_demo_003',
    payment_method: 'razorpay',
    tracking_number: 'AUR-IN-77120',
    carrier: 'Delhivery Express',
    estimated_delivery: '2024-06-25',
    status_updated_at: '2024-06-22T09:00:00Z',
    created_at: '2024-06-21T09:15:00Z',
    address: {
      full_name: 'Ananya Bose', email: 'ananya.bose@example.com', phone: '+91 90071 22334',
      line1: '221 Salt Lake Sector V', line2: '', city: 'Kolkata', state: 'West Bengal',
      pincode: '700091', country: 'India',
    },
    order_items: [
      { id: 'oi3', product_name: "Nuit d'Or Parfum", price: 45000, quantity: 1,
        products: { name: "Nuit d'Or Parfum", emoji: '🌹' } },
    ],
  },
  {
    id: 'a4444444-4444-4444-8444-444444444444',
    user_id: 'demo-user-4',
    customer_name: 'Vikram Nair',
    status: 'delivered',
    subtotal: 185000,
    tax: 33300,
    total: 218300,
    payment_id: 'pay_demo_004',
    payment_method: 'razorpay',
    tracking_number: 'AUR-IN-65932',
    carrier: 'Bluedart Premium',
    estimated_delivery: '2024-06-25',
    status_updated_at: '2024-06-24T13:40:00Z',
    created_at: '2024-06-22T16:45:00Z',
    address: {
      full_name: 'Vikram Nair', email: 'vikram.nair@example.com', phone: '+91 98450 99887',
      line1: '45 MG Road', line2: 'Indiranagar', city: 'Bengaluru', state: 'Karnataka',
      pincode: '560038', country: 'India',
    },
    order_items: [
      { id: 'oi4', product_name: 'Windsor Briefcase Obsidian', price: 185000, quantity: 1,
        products: { name: 'Windsor Briefcase Obsidian', emoji: '💼' } },
    ],
  },
];
